
<template>
  <StackLayout>
    <TableView
    :headerFields="headerFields"
    :data="userData"
    :rowSelection="true"
    notFoundMsg="Data cannot be found!"
    >
    <!-- Pagination component as a slot, but could be drag out from Database element -->
      <Pagination
        slot="pagination"
        :totalItems="50"
        :page="1"
      />
      <ItemsPerPageDropDown
        slot="ItemsPerPage"
        label="Items per page"
        :listItemsPerPage="[5, 10, 20, 50, 100]"
      />
    </TableView>
  </StackLayout>
</template>

<script>
import TableView from '../../../src/core/components/TableView/TableView';
import Pagination from '../../../src/core/components/Pagination/Pagination';
import ItemsPerPageDropDown from '../../../src/core/components/Pagination/ItemsPerPageDropDown';
import Label from '../../../src/core/components/Label/Label';
import StackLayout from '../../../src/layouts/StackLayout';

export default {
  name: 'SliderDoc',
  components: {
    StackLayout,
    TableView,
    Label,
    ItemsPerPageDropDown,
    Pagination,
  },
  data() {
    return {
      userData: [
          {
              "userId": 1,
              "type": "Person",
              "username": "Jenelle",
              "alias": "afolonin0",
              "userAccountEmail": "afolonin0@privacy.gov.au",
              "password": "arMM2S",
              "firstName": "Amaleta",
              "lastName": "Folonin",
              "photo": "http://dummyimage.com/209x177.bmp/5fa2dd/ffffff",
              "phoneNumber": "406-737-8354",
              "addressText": "73980 Elka Court",
              "streetAddress": "9012 Golden Leaf Trail",
              "mobileNumber": "486-150-9806",
              "jobTitle": "Junior Executive",
              "description": "Distributed reciprocal ability",
              "createdDate": "4/22/2019",
              "updatedDate": "5/29/2018",
              "lead": "afolonin0"
          },
          {
              "userId": 2,
              "type": "Person",
              "username": "Malvina",
              "alias": "rkinneir1",
              "userAccountEmail": "rkinneir1@deliciousdays.com",
              "password": "Lero6xsQgDM",
              "firstName": "Rodolfo",
              "lastName": "Kinneir",
              "photo": "http://dummyimage.com/198x120.bmp/dddddd/000000",
              "phoneNumber": "758-345-3330",
              "addressText": "8 Londonderry Avenue",
              "streetAddress": "7 Barnett Avenue",
              "mobileNumber": "765-920-1913",
              "jobTitle": "Media Manager II",
              "description": "Operative even-keeled system engine",
              "createdDate": "11/26/2018",
              "updatedDate": "8/10/2018",
              "lead": "rkinneir1"
          },
          {
              "userId": 3,
              "type": "Person",
              "username": "Chandler",
              "alias": "mlynds2",
              "userAccountEmail": "mlynds2@home.pl",
              "password": "E8dXIRp",
              "firstName": "Matteo",
              "lastName": "Lynds",
              "photo": "http://dummyimage.com/190x239.png/5fa2dd/ffffff",
              "phoneNumber": "431-883-0314",
              "addressText": "17772 Cherokee Trail",
              "streetAddress": "461 Southridge Way",
              "mobileNumber": "302-219-3404",
              "jobTitle": "Research Associate",
              "description": "Fully-configurable exuding policy",
              "createdDate": "9/11/2018",
              "updatedDate": "6/20/2018",
              "lead": "mlynds2"
          },
          {
              "userId": 4,
              "type": "Person",
              "username": "Yvor",
              "alias": "jmenichino3",
              "userAccountEmail": "jmenichino3@ucoz.com",
              "password": "Sv9lcJFpXQ",
              "firstName": "Jacquette",
              "lastName": "Menichino",
              "photo": "http://dummyimage.com/105x125.bmp/5fa2dd/ffffff",
              "phoneNumber": "594-145-8093",
              "addressText": "13158 Northport Trail",
              "streetAddress": "9 Summit Junction",
              "mobileNumber": "197-908-5926",
              "jobTitle": "Pharmacist",
              "description": "Networked value-added collaboration",
              "createdDate": "7/10/2018",
              "updatedDate": "3/8/2019",
              "lead": "jmenichino3"
          },
          {
              "userId": 5,
              "type": "Person",
              "username": "Mathian",
              "alias": "kcarslaw4",
              "userAccountEmail": "kcarslaw4@smh.com.au",
              "password": "2f5n2uszr12a",
              "firstName": "Kendra",
              "lastName": "Carslaw",
              "photo": "http://dummyimage.com/156x212.png/ff4444/ffffff",
              "phoneNumber": "966-745-9019",
              "addressText": "6356 Lotheville Avenue",
              "streetAddress": "0 Oxford Park",
              "mobileNumber": "126-495-3747",
              "jobTitle": "Statistician II",
              "description": "Diverse needs-based concept",
              "createdDate": "1/8/2019",
              "updatedDate": "3/21/2019",
              "lead": "kcarslaw4"
          },
          {
              "userId": 6,
              "type": "Person",
              "username": "Sibley",
              "alias": "lgiabucci5",
              "userAccountEmail": "lgiabucci5@intel.com",
              "password": "wPlZvAjPKIS",
              "firstName": "Lisha",
              "lastName": "Giabucci",
              "photo": "http://dummyimage.com/233x211.jpg/5fa2dd/ffffff",
              "phoneNumber": "295-864-4684",
              "addressText": "8 Erie Trail",
              "streetAddress": "0 Grayhawk Parkway",
              "mobileNumber": "485-822-6793",
              "jobTitle": "Environmental Specialist",
              "description": "Focused didactic archive",
              "createdDate": "12/29/2018",
              "updatedDate": "4/12/2019",
              "lead": "lgiabucci5"
          },
          {
              "userId": 7,
              "type": "Person",
              "username": "Tine",
              "alias": "aswaton6",
              "userAccountEmail": "aswaton6@exblog.jp",
              "password": "Jrclgp5N",
              "firstName": "Agata",
              "lastName": "Swaton",
              "photo": "http://dummyimage.com/214x158.bmp/ff4444/ffffff",
              "phoneNumber": "870-124-1814",
              "addressText": "1049 Ruskin Junction",
              "streetAddress": "0025 Dahle Road",
              "mobileNumber": "506-696-5281",
              "jobTitle": "Administrative Officer",
              "description": "Re-contextualized heuristic alliance",
              "createdDate": "1/9/2019",
              "updatedDate": "2/19/2019",
              "lead": "aswaton6"
          },
          {
              "userId": 8,
              "type": "Person",
              "username": "Eve",
              "alias": "jsember7",
              "userAccountEmail": "jsember7@si.edu",
              "password": "CTO6P6hy",
              "firstName": "Johnath",
              "lastName": "Sember",
              "photo": "http://dummyimage.com/176x122.jpg/ff4444/ffffff",
              "phoneNumber": "763-651-4182",
              "addressText": "98 Jenifer Alley",
              "streetAddress": "2 Hauk Place",
              "mobileNumber": "669-585-5282",
              "jobTitle": "Cost Accountant",
              "description": "Optional high-level instruction set",
              "createdDate": "7/18/2018",
              "updatedDate": "10/23/2018",
              "lead": "jsember7"
          },
          {
              "userId": 9,
              "type": "Person",
              "username": "Karlee",
              "alias": "mstirman8",
              "userAccountEmail": "mstirman8@ycombinator.com",
              "password": "Pqst9k5Aw",
              "firstName": "Minne",
              "lastName": "Stirman",
              "photo": "http://dummyimage.com/103x183.jpg/dddddd/000000",
              "phoneNumber": "199-231-9030",
              "addressText": "962 Scofield Park",
              "streetAddress": "64836 Eastlawn Point",
              "mobileNumber": "395-531-6919",
              "jobTitle": "Internal Auditor",
              "description": "Stand-alone next generation attitude",
              "createdDate": "8/1/2018",
              "updatedDate": "4/16/2019",
              "lead": "mstirman8"
          },
          {
              "userId": 10,
              "type": "Person",
              "username": "Andromache",
              "alias": "sduguid9",
              "userAccountEmail": "sduguid9@dmoz.org",
              "password": "vCEWM2Ss",
              "firstName": "Syd",
              "lastName": "Duguid",
              "photo": "http://dummyimage.com/103x161.jpg/dddddd/000000",
              "phoneNumber": "984-230-1613",
              "addressText": "51329 Granby Road",
              "streetAddress": "7 Arizona Way",
              "mobileNumber": "563-438-1034",
              "jobTitle": "Statistician IV",
              "description": "Cross-platform stable implementation",
              "createdDate": "9/9/2018",
              "updatedDate": "3/2/2019",
              "lead": "sduguid9"
          },
          {
              "userId": 11,
              "type": "Person",
              "username": "Jana",
              "alias": "rmichallata",
              "userAccountEmail": "rmichallata@about.com",
              "password": "S1sxXcl0VTAW",
              "firstName": "Ryann",
              "lastName": "Michallat",
              "photo": "http://dummyimage.com/135x137.jpg/dddddd/000000",
              "phoneNumber": "123-187-9191",
              "addressText": "3 Banding Way",
              "streetAddress": "5368 Maywood Way",
              "mobileNumber": "794-969-9499",
              "jobTitle": "Help Desk Technician",
              "description": "Total 24/7 projection",
              "createdDate": "9/12/2018",
              "updatedDate": "1/27/2019",
              "lead": "rmichallata"
          },
          {
              "userId": 12,
              "type": "Person",
              "username": "Malissa",
              "alias": "jreveningb",
              "userAccountEmail": "jreveningb@ocn.ne.jp",
              "password": "KpKvzq",
              "firstName": "Justin",
              "lastName": "Revening",
              "photo": "http://dummyimage.com/165x166.png/5fa2dd/ffffff",
              "phoneNumber": "817-494-0713",
              "addressText": "4968 Nevada Plaza",
              "streetAddress": "54 Spaight Pass",
              "mobileNumber": "794-718-0644",
              "jobTitle": "Health Coach I",
              "description": "Proactive next generation methodology",
              "createdDate": "7/16/2018",
              "updatedDate": "12/6/2018",
              "lead": "jreveningb"
          },
          {
              "userId": 13,
              "type": "Person",
              "username": "Harley",
              "alias": "skermitc",
              "userAccountEmail": "skermitc@google.com.hk",
              "password": "6JHSKZ",
              "firstName": "Susann",
              "lastName": "Kermit",
              "photo": "http://dummyimage.com/190x236.png/5fa2dd/ffffff",
              "phoneNumber": "450-356-4184",
              "addressText": "42 Sloan Place",
              "streetAddress": "0 Waywood Alley",
              "mobileNumber": "130-620-3618",
              "jobTitle": "Compensation Analyst",
              "description": "Cross-group radical implementation",
              "createdDate": "11/24/2018",
              "updatedDate": "6/29/2018",
              "lead": "skermitc"
          },
          {
              "userId": 14,
              "type": "Person",
              "username": "Maxy",
              "alias": "wrodriguezd",
              "userAccountEmail": "wrodriguezd@disqus.com",
              "password": "taDaRdBr",
              "firstName": "Wallie",
              "lastName": "Rodriguez",
              "photo": "http://dummyimage.com/162x166.jpg/cc0000/ffffff",
              "phoneNumber": "635-391-4116",
              "addressText": "4714 Rieder Parkway",
              "streetAddress": "6236 Anthes Road",
              "mobileNumber": "749-153-2323",
              "jobTitle": "Environmental Specialist",
              "description": "Re-engineered cohesive knowledge base",
              "createdDate": "2/2/2019",
              "updatedDate": "6/17/2018",
              "lead": "wrodriguezd"
          },
          {
              "userId": 15,
              "type": "Person",
              "username": "Scot",
              "alias": "landrolettie",
              "userAccountEmail": "landrolettie@google.co.uk",
              "password": "J9wPzCgV7MM",
              "firstName": "Lalo",
              "lastName": "Androletti",
              "photo": "http://dummyimage.com/118x174.png/cc0000/ffffff",
              "phoneNumber": "151-800-9196",
              "addressText": "8721 Waubesa Court",
              "streetAddress": "87225 Continental Terrace",
              "mobileNumber": "160-286-3646",
              "jobTitle": "Technical Writer",
              "description": "Monitored asymmetric firmware",
              "createdDate": "11/22/2018",
              "updatedDate": "6/26/2018",
              "lead": "landrolettie"
          },
          {
              "userId": 16,
              "type": "Person",
              "username": "Mackenzie",
              "alias": "olesaunierf",
              "userAccountEmail": "olesaunierf@plala.or.jp",
              "password": "6WR92Y3",
              "firstName": "Obed",
              "lastName": "Lesaunier",
              "photo": "http://dummyimage.com/218x177.jpg/5fa2dd/ffffff",
              "phoneNumber": "737-906-9862",
              "addressText": "258 Loomis Pass",
              "streetAddress": "55975 Briar Crest Park",
              "mobileNumber": "987-613-4245",
              "jobTitle": "Associate Professor",
              "description": "Streamlined static local area network",
              "createdDate": "2/20/2019",
              "updatedDate": "2/18/2019",
              "lead": "olesaunierf"
          },
          {
              "userId": 17,
              "type": "Person",
              "username": "Kenyon",
              "alias": "msqueersg",
              "userAccountEmail": "msqueersg@about.com",
              "password": "XaWktFH",
              "firstName": "Micheal",
              "lastName": "Squeers",
              "photo": "http://dummyimage.com/118x138.bmp/cc0000/ffffff",
              "phoneNumber": "785-530-0355",
              "addressText": "32700 Corry Court",
              "streetAddress": "07507 Mandrake Place",
              "mobileNumber": "956-760-7129",
              "jobTitle": "Chemical Engineer",
              "description": "Balanced discrete utilisation",
              "createdDate": "10/9/2018",
              "updatedDate": "6/22/2018",
              "lead": "msqueersg"
          },
          {
              "userId": 18,
              "type": "Person",
              "username": "Danice",
              "alias": "wburburoughh",
              "userAccountEmail": "wburburoughh@addthis.com",
              "password": "w6OTUiyr59aX",
              "firstName": "Wynny",
              "lastName": "Burburough",
              "photo": "http://dummyimage.com/116x247.bmp/dddddd/000000",
              "phoneNumber": "926-143-2788",
              "addressText": "502 Drewry Road",
              "streetAddress": "825 Russell Trail",
              "mobileNumber": "793-300-1793",
              "jobTitle": "Sales Representative",
              "description": "Optional attitude-oriented alliance",
              "createdDate": "6/27/2018",
              "updatedDate": "11/11/2018",
              "lead": "wburburoughh"
          },
          {
              "userId": 19,
              "type": "Person",
              "username": "Orv",
              "alias": "toregani",
              "userAccountEmail": "toregani@mashable.com",
              "password": "FgHEm9V0Xith",
              "firstName": "Timi",
              "lastName": "O'Regan",
              "photo": "http://dummyimage.com/181x169.png/5fa2dd/ffffff",
              "phoneNumber": "308-401-3235",
              "addressText": "8 Forest Run Center",
              "streetAddress": "5954 Bultman Road",
              "mobileNumber": "712-599-5978",
              "jobTitle": "Health Coach I",
              "description": "Digitized heuristic methodology",
              "createdDate": "6/28/2018",
              "updatedDate": "12/7/2018",
              "lead": "toregani"
          },
          {
              "userId": 20,
              "type": "Person",
              "username": "Glyn",
              "alias": "mluffmanj",
              "userAccountEmail": "mluffmanj@businessweek.com",
              "password": "nvnfA2Tf",
              "firstName": "Milzie",
              "lastName": "Luffman",
              "photo": "http://dummyimage.com/150x228.png/ff4444/ffffff",
              "phoneNumber": "832-574-4848",
              "addressText": "4 Kinsman Hill",
              "streetAddress": "960 Westport Drive",
              "mobileNumber": "775-823-6217",
              "jobTitle": "Assistant Professor",
              "description": "Innovative reciprocal groupware",
              "createdDate": "12/19/2018",
              "updatedDate": "12/12/2018",
              "lead": "mluffmanj"
          },
          {
              "userId": 21,
              "type": "Person",
              "username": "Shelley",
              "alias": "dstreetenk",
              "userAccountEmail": "dstreetenk@independent.co.uk",
              "password": "DNwee7BqAcU",
              "firstName": "Darb",
              "lastName": "Streeten",
              "photo": "http://dummyimage.com/102x216.png/cc0000/ffffff",
              "phoneNumber": "493-125-8365",
              "addressText": "1998 Prentice Avenue",
              "streetAddress": "56 Artisan Drive",
              "mobileNumber": "728-124-5446",
              "jobTitle": "Electrical Engineer",
              "description": "Ergonomic bifurcated array",
              "createdDate": "6/26/2018",
              "updatedDate": "12/27/2018",
              "lead": "dstreetenk"
          },
          {
              "userId": 22,
              "type": "Person",
              "username": "Gabriellia",
              "alias": "cboudal",
              "userAccountEmail": "cboudal@bbc.co.uk",
              "password": "2JQ8rn",
              "firstName": "Cully",
              "lastName": "Bouda",
              "photo": "http://dummyimage.com/208x150.bmp/ff4444/ffffff",
              "phoneNumber": "672-308-9481",
              "addressText": "38619 Stoughton Hill",
              "streetAddress": "9 New Castle Trail",
              "mobileNumber": "590-513-1853",
              "jobTitle": "Developer I",
              "description": "Balanced leading edge parallelism",
              "createdDate": "1/7/2019",
              "updatedDate": "12/24/2018",
              "lead": "cboudal"
          },
          {
              "userId": 23,
              "type": "Person",
              "username": "Reynolds",
              "alias": "schappellem",
              "userAccountEmail": "schappellem@blogspot.com",
              "password": "OVSBmd",
              "firstName": "Sharon",
              "lastName": "Chappelle",
              "photo": "http://dummyimage.com/213x198.bmp/5fa2dd/ffffff",
              "phoneNumber": "840-889-3653",
              "addressText": "601 Anhalt Street",
              "streetAddress": "4967 Debra Road",
              "mobileNumber": "405-826-6198",
              "jobTitle": "Food Chemist",
              "description": "Re-contextualized secondary capability",
              "createdDate": "3/14/2019",
              "updatedDate": "2/16/2019",
              "lead": "schappellem"
          },
          {
              "userId": 24,
              "type": "Person",
              "username": "Emmerich",
              "alias": "jdubbinn",
              "userAccountEmail": "jdubbinn@networksolutions.com",
              "password": "VMQh62k",
              "firstName": "Jud",
              "lastName": "Dubbin",
              "photo": "http://dummyimage.com/171x225.bmp/dddddd/000000",
              "phoneNumber": "814-672-6710",
              "addressText": "9160 Raven Court",
              "streetAddress": "487 Merry Road",
              "mobileNumber": "678-377-5177",
              "jobTitle": "Financial Analyst",
              "description": "Operative methodical parallelism",
              "createdDate": "2/23/2019",
              "updatedDate": "8/19/2018",
              "lead": "jdubbinn"
          },
          {
              "userId": 25,
              "type": "Person",
              "username": "Lori",
              "alias": "eliliono",
              "userAccountEmail": "eliliono@scribd.com",
              "password": "0zaG3EC",
              "firstName": "Elihu",
              "lastName": "Lilion",
              "photo": "http://dummyimage.com/126x199.jpg/dddddd/000000",
              "phoneNumber": "909-613-1927",
              "addressText": "540 Lien Circle",
              "streetAddress": "1837 Daystar Center",
              "mobileNumber": "138-911-5987",
              "jobTitle": "Human Resources Assistant II",
              "description": "Switchable zero administration secured line",
              "createdDate": "8/10/2018",
              "updatedDate": "8/23/2018",
              "lead": "eliliono"
          },
          {
              "userId": 26,
              "type": "Person",
              "username": "Annamarie",
              "alias": "idoweyp",
              "userAccountEmail": "idoweyp@newsvine.com",
              "password": "vYfhmWfX18",
              "firstName": "Isaak",
              "lastName": "Dowey",
              "photo": "http://dummyimage.com/248x241.bmp/5fa2dd/ffffff",
              "phoneNumber": "566-346-7874",
              "addressText": "161 Moose Point",
              "streetAddress": "9974 Fieldstone Park",
              "mobileNumber": "131-842-1407",
              "jobTitle": "Tax Accountant",
              "description": "Proactive homogeneous infrastructure",
              "createdDate": "9/23/2018",
              "updatedDate": "11/28/2018",
              "lead": "idoweyp"
          },
          {
              "userId": 27,
              "type": "Person",
              "username": "Wanids",
              "alias": "sbertelmotq",
              "userAccountEmail": "sbertelmotq@jiathis.com",
              "password": "JmUkV8fDhv",
              "firstName": "Sal",
              "lastName": "Bertelmot",
              "photo": "http://dummyimage.com/228x228.png/ff4444/ffffff",
              "phoneNumber": "681-989-2268",
              "addressText": "9 Weeping Birch Drive",
              "streetAddress": "474 Banding Point",
              "mobileNumber": "964-590-2564",
              "jobTitle": "Office Assistant II",
              "description": "Progressive incremental archive",
              "createdDate": "7/12/2018",
              "updatedDate": "1/28/2019",
              "lead": "sbertelmotq"
          },
          {
              "userId": 28,
              "type": "Person",
              "username": "Tim",
              "alias": "rthodayr",
              "userAccountEmail": "rthodayr@hatena.ne.jp",
              "password": "nPfkfaia",
              "firstName": "Reggie",
              "lastName": "Thoday",
              "photo": "http://dummyimage.com/249x236.jpg/ff4444/ffffff",
              "phoneNumber": "469-440-2269",
              "addressText": "1411 Schmedeman Avenue",
              "streetAddress": "65 Express Plaza",
              "mobileNumber": "654-800-7809",
              "jobTitle": "Programmer Analyst IV",
              "description": "Triple-buffered executive frame",
              "createdDate": "4/6/2019",
              "updatedDate": "5/17/2019",
              "lead": "rthodayr"
          },
          {
              "userId": 29,
              "type": "Person",
              "username": "Moshe",
              "alias": "gpickwells",
              "userAccountEmail": "gpickwells@blinklist.com",
              "password": "5TZhtzm8",
              "firstName": "Georgie",
              "lastName": "Pickwell",
              "photo": "http://dummyimage.com/153x102.bmp/dddddd/000000",
              "phoneNumber": "559-912-2591",
              "addressText": "5239 Petterle Center",
              "streetAddress": "2 Columbus Point",
              "mobileNumber": "623-914-7347",
              "jobTitle": "Social Worker",
              "description": "Extended global database",
              "createdDate": "1/8/2019",
              "updatedDate": "9/25/2018",
              "lead": "gpickwells"
          },
          {
              "userId": 30,
              "type": "Person",
              "username": "Raynell",
              "alias": "msilvestont",
              "userAccountEmail": "msilvestont@cdbaby.com",
              "password": "LRmyziX9",
              "firstName": "Monty",
              "lastName": "Silveston",
              "photo": "http://dummyimage.com/226x237.bmp/5fa2dd/ffffff",
              "phoneNumber": "931-291-5408",
              "addressText": "5 Boyd Place",
              "streetAddress": "72 Northland Lane",
              "mobileNumber": "732-916-2065",
              "jobTitle": "Human Resources Assistant IV",
              "description": "Extended clear-thinking instruction set",
              "createdDate": "6/12/2018",
              "updatedDate": "2/1/2019",
              "lead": "msilvestont"
          },
          {
              "userId": 31,
              "type": "Person",
              "username": "Carmine",
              "alias": "sministeru",
              "userAccountEmail": "sministeru@mashable.com",
              "password": "TJ1vdpd9mX4R",
              "firstName": "Shelley",
              "lastName": "Minister",
              "photo": "http://dummyimage.com/180x236.jpg/5fa2dd/ffffff",
              "phoneNumber": "581-151-2237",
              "addressText": "3141 Farwell Avenue",
              "streetAddress": "4 Thierer Junction",
              "mobileNumber": "126-115-5959",
              "jobTitle": "Administrative Assistant IV",
              "description": "Cross-group human-resource Graphical User Interface",
              "createdDate": "8/26/2018",
              "updatedDate": "4/2/2019",
              "lead": "sministeru"
          },
          {
              "userId": 32,
              "type": "Person",
              "username": "Lemmie",
              "alias": "kmartonfiv",
              "userAccountEmail": "kmartonfiv@ehow.com",
              "password": "yoOMJg9xh62",
              "firstName": "Karie",
              "lastName": "Martonfi",
              "photo": "http://dummyimage.com/181x240.jpg/dddddd/000000",
              "phoneNumber": "474-858-9777",
              "addressText": "3 Ridgeway Street",
              "streetAddress": "79253 Farragut Plaza",
              "mobileNumber": "914-599-3380",
              "jobTitle": "GIS Technical Architect",
              "description": "Future-proofed explicit pricing structure",
              "createdDate": "4/12/2019",
              "updatedDate": "7/13/2018",
              "lead": "kmartonfiv"
          },
          {
              "userId": 33,
              "type": "Person",
              "username": "Deck",
              "alias": "cchaimsonw",
              "userAccountEmail": "cchaimsonw@myspace.com",
              "password": "2CQ2gwJG",
              "firstName": "Charita",
              "lastName": "Chaimson",
              "photo": "http://dummyimage.com/191x150.bmp/ff4444/ffffff",
              "phoneNumber": "333-111-1127",
              "addressText": "94 Stephen Park",
              "streetAddress": "309 East Junction",
              "mobileNumber": "645-585-2496",
              "jobTitle": "Financial Advisor",
              "description": "Re-engineered foreground software",
              "createdDate": "2/16/2019",
              "updatedDate": "9/22/2018",
              "lead": "cchaimsonw"
          },
          {
              "userId": 34,
              "type": "Person",
              "username": "Darryl",
              "alias": "msparhamx",
              "userAccountEmail": "msparhamx@yahoo.co.jp",
              "password": "p6aJCK",
              "firstName": "Mame",
              "lastName": "Sparham",
              "photo": "http://dummyimage.com/164x150.jpg/ff4444/ffffff",
              "phoneNumber": "805-270-2776",
              "addressText": "3 Hoepker Street",
              "streetAddress": "68322 Nancy Way",
              "mobileNumber": "170-872-9584",
              "jobTitle": "Associate Professor",
              "description": "Reactive dedicated algorithm",
              "createdDate": "4/26/2019",
              "updatedDate": "10/22/2018",
              "lead": "msparhamx"
          },
          {
              "userId": 35,
              "type": "Person",
              "username": "Starlene",
              "alias": "ddejuaresy",
              "userAccountEmail": "ddejuaresy@slashdot.org",
              "password": "y9omxcyaQN",
              "firstName": "Dyan",
              "lastName": "de Juares",
              "photo": "http://dummyimage.com/231x112.jpg/ff4444/ffffff",
              "phoneNumber": "495-267-2180",
              "addressText": "5 Nevada Point",
              "streetAddress": "90 Armistice Point",
              "mobileNumber": "532-155-5856",
              "jobTitle": "Project Manager",
              "description": "Grass-roots mission-critical support",
              "createdDate": "8/29/2018",
              "updatedDate": "5/2/2019",
              "lead": "ddejuaresy"
          },
          {
              "userId": 36,
              "type": "Person",
              "username": "Clarence",
              "alias": "jcasinz",
              "userAccountEmail": "jcasinz@bbb.org",
              "password": "uN6Rnasv",
              "firstName": "Joeann",
              "lastName": "Casin",
              "photo": "http://dummyimage.com/178x229.bmp/5fa2dd/ffffff",
              "phoneNumber": "568-765-3603",
              "addressText": "753 Norway Maple Hill",
              "streetAddress": "7 Maple Wood Pass",
              "mobileNumber": "718-194-8950",
              "jobTitle": "Web Designer I",
              "description": "Organized cohesive migration",
              "createdDate": "2/23/2019",
              "updatedDate": "2/16/2019",
              "lead": "jcasinz"
          },
          {
              "userId": 37,
              "type": "Person",
              "username": "Ximenes",
              "alias": "jkleinzweig10",
              "userAccountEmail": "jkleinzweig10@discovery.com",
              "password": "Dlc3E4",
              "firstName": "Jehanna",
              "lastName": "Kleinzweig",
              "photo": "http://dummyimage.com/162x231.bmp/ff4444/ffffff",
              "phoneNumber": "700-899-3190",
              "addressText": "1975 Grasskamp Pass",
              "streetAddress": "8517 Moland Parkway",
              "mobileNumber": "572-793-7040",
              "jobTitle": "Engineer III",
              "description": "Centralized holistic service-desk",
              "createdDate": "8/12/2018",
              "updatedDate": "5/4/2019",
              "lead": "jkleinzweig10"
          },
          {
              "userId": 38,
              "type": "Person",
              "username": "Pammy",
              "alias": "areast11",
              "userAccountEmail": "areast11@list-manage.com",
              "password": "8X8tSoeh",
              "firstName": "Angelle",
              "lastName": "Reast",
              "photo": "http://dummyimage.com/230x109.png/ff4444/ffffff",
              "phoneNumber": "173-103-0999",
              "addressText": "6909 Springs Hill",
              "streetAddress": "4057 Swallow Drive",
              "mobileNumber": "803-702-9016",
              "jobTitle": "Programmer Analyst IV",
              "description": "Balanced regional matrix",
              "createdDate": "2/2/2019",
              "updatedDate": "8/7/2018",
              "lead": "areast11"
          },
          {
              "userId": 39,
              "type": "Person",
              "username": "Germaine",
              "alias": "mskechley12",
              "userAccountEmail": "mskechley12@miitbeian.gov.cn",
              "password": "QH938TPnX4f",
              "firstName": "Marieann",
              "lastName": "Skechley",
              "photo": "http://dummyimage.com/158x157.bmp/ff4444/ffffff",
              "phoneNumber": "799-175-9496",
              "addressText": "50 Knutson Circle",
              "streetAddress": "9 Helena Parkway",
              "mobileNumber": "591-349-6950",
              "jobTitle": "Actuary",
              "description": "Multi-channelled context-sensitive capability",
              "createdDate": "7/27/2018",
              "updatedDate": "12/20/2018",
              "lead": "mskechley12"
          },
          {
              "userId": 40,
              "type": "Person",
              "username": "Ilka",
              "alias": "rboag13",
              "userAccountEmail": "rboag13@statcounter.com",
              "password": "gqR5JT",
              "firstName": "Robby",
              "lastName": "Boag",
              "photo": "http://dummyimage.com/129x175.bmp/5fa2dd/ffffff",
              "phoneNumber": "426-389-9634",
              "addressText": "00 Armistice Hill",
              "streetAddress": "282 Mesta Lane",
              "mobileNumber": "904-781-0741",
              "jobTitle": "Marketing Assistant",
              "description": "Polarised full-range task-force",
              "createdDate": "2/24/2019",
              "updatedDate": "4/7/2019",
              "lead": "rboag13"
          },
          {
              "userId": 41,
              "type": "Person",
              "username": "Fletcher",
              "alias": "bhardiker14",
              "userAccountEmail": "bhardiker14@sfgate.com",
              "password": "SIbx6Y3Ih",
              "firstName": "Broderic",
              "lastName": "Hardiker",
              "photo": "http://dummyimage.com/229x111.bmp/ff4444/ffffff",
              "phoneNumber": "935-370-6131",
              "addressText": "9 Pankratz Center",
              "streetAddress": "6 Twin Pines Point",
              "mobileNumber": "380-572-6364",
              "jobTitle": "Speech Pathologist",
              "description": "Reactive dedicated knowledge base",
              "createdDate": "3/19/2019",
              "updatedDate": "6/13/2018",
              "lead": "bhardiker14"
          },
          {
              "userId": 42,
              "type": "Person",
              "username": "Kirstyn",
              "alias": "drichens15",
              "userAccountEmail": "drichens15@tripod.com",
              "password": "1Ip6S87Zd3",
              "firstName": "Dagny",
              "lastName": "Richens",
              "photo": "http://dummyimage.com/144x204.bmp/dddddd/000000",
              "phoneNumber": "417-315-1404",
              "addressText": "6655 South Center",
              "streetAddress": "87 Northview Street",
              "mobileNumber": "954-633-8382",
              "jobTitle": "Assistant Manager",
              "description": "Distributed leading edge core",
              "createdDate": "4/24/2019",
              "updatedDate": "4/8/2019",
              "lead": "drichens15"
          },
          {
              "userId": 43,
              "type": "Person",
              "username": "Maxy",
              "alias": "eandreuzzi16",
              "userAccountEmail": "eandreuzzi16@myspace.com",
              "password": "2qKxHp5eAza7",
              "firstName": "Elaina",
              "lastName": "Andreuzzi",
              "photo": "http://dummyimage.com/198x139.png/ff4444/ffffff",
              "phoneNumber": "513-830-0910",
              "addressText": "23582 Bartillon Point",
              "streetAddress": "26 1st Junction",
              "mobileNumber": "865-182-2302",
              "jobTitle": "Financial Analyst",
              "description": "Customer-focused explicit pricing structure",
              "createdDate": "6/6/2018",
              "updatedDate": "1/22/2019",
              "lead": "eandreuzzi16"
          },
          {
              "userId": 44,
              "type": "Person",
              "username": "Hettie",
              "alias": "npercy17",
              "userAccountEmail": "npercy17@reddit.com",
              "password": "dNYgwKw64",
              "firstName": "Nickey",
              "lastName": "Percy",
              "photo": "http://dummyimage.com/106x155.png/ff4444/ffffff",
              "phoneNumber": "970-409-7123",
              "addressText": "96 Artisan Trail",
              "streetAddress": "934 Ronald Regan Point",
              "mobileNumber": "512-212-8576",
              "jobTitle": "Assistant Professor",
              "description": "Re-engineered neutral extranet",
              "createdDate": "6/12/2018",
              "updatedDate": "6/4/2018",
              "lead": "npercy17"
          },
          {
              "userId": 45,
              "type": "Person",
              "username": "Cariotta",
              "alias": "tkynoch18",
              "userAccountEmail": "tkynoch18@vistaprint.com",
              "password": "GBvwucH812T",
              "firstName": "Tarah",
              "lastName": "Kynoch",
              "photo": "http://dummyimage.com/157x225.bmp/dddddd/000000",
              "phoneNumber": "452-591-8191",
              "addressText": "33311 Burrows Crossing",
              "streetAddress": "48815 Oneill Alley",
              "mobileNumber": "598-903-8407",
              "jobTitle": "Systems Administrator III",
              "description": "Exclusive needs-based installation",
              "createdDate": "6/12/2018",
              "updatedDate": "8/2/2018",
              "lead": "tkynoch18"
          },
          {
              "userId": 46,
              "type": "Person",
              "username": "Charlean",
              "alias": "ebeange19",
              "userAccountEmail": "ebeange19@spotify.com",
              "password": "otMquHlD",
              "firstName": "Ernie",
              "lastName": "Beange",
              "photo": "http://dummyimage.com/188x197.bmp/5fa2dd/ffffff",
              "phoneNumber": "510-840-3982",
              "addressText": "4167 Elka Way",
              "streetAddress": "3 Kedzie Hill",
              "mobileNumber": "762-903-8569",
              "jobTitle": "Senior Sales Associate",
              "description": "Switchable explicit complexity",
              "createdDate": "11/14/2018",
              "updatedDate": "10/29/2018",
              "lead": "ebeange19"
          },
          {
              "userId": 47,
              "type": "Person",
              "username": "Carolina",
              "alias": "epfiffer1a",
              "userAccountEmail": "epfiffer1a@digg.com",
              "password": "HQjHMtz",
              "firstName": "Evelyn",
              "lastName": "Pfiffer",
              "photo": "http://dummyimage.com/140x104.bmp/ff4444/ffffff",
              "phoneNumber": "416-260-4705",
              "addressText": "4 Nova Alley",
              "streetAddress": "6 Corscot Circle",
              "mobileNumber": "534-971-5283",
              "jobTitle": "Media Manager II",
              "description": "Reactive content-based challenge",
              "createdDate": "11/20/2018",
              "updatedDate": "6/23/2018",
              "lead": "epfiffer1a"
          },
          {
              "userId": 48,
              "type": "Person",
              "username": "Davina",
              "alias": "bsaltwell1b",
              "userAccountEmail": "bsaltwell1b@gravatar.com",
              "password": "eYK4jrx13H7H",
              "firstName": "Bryn",
              "lastName": "Saltwell",
              "photo": "http://dummyimage.com/227x179.jpg/cc0000/ffffff",
              "phoneNumber": "368-221-7178",
              "addressText": "55 Bowman Point",
              "streetAddress": "17 Fallview Avenue",
              "mobileNumber": "367-218-2604",
              "jobTitle": "Recruiter",
              "description": "Total foreground framework",
              "createdDate": "7/10/2018",
              "updatedDate": "8/9/2018",
              "lead": "bsaltwell1b"
          },
          {
              "userId": 49,
              "type": "Person",
              "username": "Sib",
              "alias": "elemonnier1c",
              "userAccountEmail": "elemonnier1c@timesonline.co.uk",
              "password": "uMU4tSaf",
              "firstName": "Enrichetta",
              "lastName": "Le Monnier",
              "photo": "http://dummyimage.com/231x203.jpg/cc0000/ffffff",
              "phoneNumber": "821-205-8821",
              "addressText": "615 Ludington Pass",
              "streetAddress": "9686 Westport Circle",
              "mobileNumber": "633-851-1172",
              "jobTitle": "Administrative Assistant II",
              "description": "Public-key secondary service-desk",
              "createdDate": "7/25/2018",
              "updatedDate": "11/22/2018",
              "lead": "elemonnier1c"
          },
          {
              "userId": 50,
              "type": "Person",
              "username": "Heida",
              "alias": "iheigl1d",
              "userAccountEmail": "iheigl1d@xing.com",
              "password": "dvyQYqP4",
              "firstName": "Issie",
              "lastName": "Heigl",
              "photo": "http://dummyimage.com/156x106.bmp/cc0000/ffffff",
              "phoneNumber": "356-820-6008",
              "addressText": "63 Jenna Avenue",
              "streetAddress": "66 Ilene Court",
              "mobileNumber": "172-854-6528",
              "jobTitle": "Editor",
              "description": "Business-focused zero tolerance task-force",
              "createdDate": "4/1/2019",
              "updatedDate": "6/15/2018",
              "lead": "iheigl1d"
          }
      ],
      headerFields: [
        {
          type: "image",
          name: "photo",
          label: "Photo",
          sortable: false,
          listAlignment: 'horizontal',
        },
        {
          type: "text",
          name: "username",
          label: "user name",
          sortable: false,
          listAlignment: 'horizontal',
        },
        {
          type: "text",
          name: "firstName",
          label: "first name",
          sortable: false,
          listAlignment: 'vertical',
        },
        {
          type: "text",
          name: "lastName",
          label: "Last name",
          sortable: true,
          listAlignment: 'vertical',
        },
        {
          type: "text",
          name: "mobileNumber",
          label: "mobile number",
          sortable: true,
          listAlignment: 'vertical',
        },
        {
          type: "text",
          name: "createdDate",
          label: "create date",
          sortable: true,
          listAlignment: 'vertical',
        }
      ],
    };
  },
  methods: {
  },
};
</script>
