import { createLocalVue } from '@vue/test-utils';
import Button from '../../src/components/Button';
import Img from '../../src/components/Img';
import Label from '../../src/components/Label';
import Page from '../../src/components/Page';
import Progress from '../../src/components/Progress';
import ScrollView from '../../src/components/ScrollView';
import Frame from '../../src/components/Frame';
import SearchBar from '../../src/components/SearchBar';
import SegmentedBar from '../../src/components/SegmentedBar';
import SegmentedBarItem from '../../src/components/SegmentedBarItem';
import Slider from '../../src/components/Slider';
import Switcher from '../../src/components/Switcher';
import TextField from '../../src/components/TextField';
import TextView from '../../src/components/TextView';
import ActionItem from '../../src/components/ActionItem';
import NavigationButton from '../../src/components/NavigationButton';
import ActionBar from '../../src/components/ActionBar';
import TabView from '../../src/components/TabView';
import TabViewItem from '../../src/components/TabViewItem';
import AlertDialog from '../../src/components/dialogs/AlertDialog';
import ConfirmDialog from '../../src/components/dialogs/ConfirmDialog';
import VxpLink from '../../src/components/VxpLink';
import AbsoluteLayout from '../../src/layouts/AbsoluteLayout';
import StackLayout from '../../src/layouts/StackLayout';
import DockLayout from '../../src/layouts/DockLayout';
import FlexboxLayout from '../../src/layouts/FlexboxLayout';
import GridLayout from '../../src/layouts/GridLayout';
import WrapLayout from '../../src/layouts/WrapLayout';

const localVue = createLocalVue();
localVue.component('Button', Button);

localVue.component('Img', Img);
localVue.component('Label', Label);
localVue.component('Page', Page);
localVue.component('Progress', Progress);
localVue.component('ScrollView', ScrollView);
localVue.component('Frame', Frame);
localVue.component('SearchBar', SearchBar);
localVue.component('SegmentedBar', SegmentedBar);
localVue.component('SegmentedBarItem', SegmentedBarItem);
localVue.component('Slider', Slider);
localVue.component('Switcher', Switcher);
localVue.component('TextField', TextField);
localVue.component('TextView', TextView);
localVue.component('ActionItem', ActionItem);
localVue.component('NavigationButton', NavigationButton);
localVue.component('ActionBar', ActionBar);
localVue.component('VxpLink', VxpLink);
localVue.component('TabView', TabView);
localVue.component('TabViewItem', TabViewItem);
localVue.component('AlertDialog', AlertDialog);
localVue.component('ConfirmDialog', ConfirmDialog);
localVue.component('AbsoluteLayout', AbsoluteLayout);
localVue.component('StackLayout', StackLayout);
localVue.component('DockLayout', DockLayout);
localVue.component('FlexboxLayout', FlexboxLayout);
localVue.component('GridLayout', GridLayout);
localVue.component('WrapLayout', WrapLayout);

export default localVue;
